### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by Karl1b** [uvulpos/golang-sveltekit-binary#61]
**Description**: 
Typo in
[https://github.com/uvulpos/golang-sveltekit-binary/blob/main/docs/how-to/database/new-migration/Readme.md]( https://github.com/uvulpos/golang-sveltekit-binary/blob/main/docs/how-to/database/new-migration/Readme.md)

_Go to your backend service and then to src/migrator/migration-files and create two new files: <number>_<name>.up.sql and <number>_<name>.up.sql._

**Expected Behaviour**
should be up and down migration

**Actual Behaviour**
therte is only up migration

**Additional Information:**
The preffered way of defining database queries on the tables should be documented as well.

(I expect some  way to define my database queries  as well in a sql file. 
One possible way would be to create them with sqlc. Or a hint what the preffered way of creating queries in this Techstack is)

**Comment by uvulpos** [comment]
done
